// Login/Signup (Auth) types
export const LOGIN_USER_SAGA = 'LOGIN_USER_SAGA';
export const REGISTER_USER_SAGA = 'REGISTER_USER_SAGA';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';
export const SET_USER = 'SET_USER';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const LOG_OUT_USER_SAGA = 'LOG_OUT_USER_SAGA';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const GET_THIS_USER_SAGA = 'GET_THIS_USER_SAGA';
export const SET_REG_INDEX = 'SET_REG_INDEX';

// Session/Class Redux Types
export const CREATE_NEW_SESSION_SAGA = 'CREATE_NEW_SESSION_SAGA';
export const SET_CURRENT_CREATED_SESSION = 'SET_CURRENT_CREATED_SESSION';
export const SET_SESSION_LOADING = 'SET_SESSION_LOADING';
export const GET_USER_SESSIONS_SAGA = 'GET_USER_SESSIONS';
export const SET_USER_SESSIONS_HISTORY = 'SET_USER_SESSIONS_HISTORY';
// More types...
